-- Generated from generator/demo_specs/aws-indonesia-palm-oil-trading.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-palm-oil-trading
-- This is the schema that is actually deployed for ID_PALM_OIL_TRADING.

-- Alerts fire on the bottom tail of CPO Price
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_CPO_PRICE) AS T
  FROM RAW.MARKET_PRICES
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CPO_PRICE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CPO_PRICE), 2) AS AVG_CPO_PRICE,
  ROUND(AVG(f.KPI_ROTTERDAM_CIF), 2) AS AVG_ROTTERDAM_CIF,
  ROUND(AVG(f.KPI_INDIA_IMPORT_DUTY), 2) AS AVG_INDIA_IMPORT_DUTY,
  ROUND(AVG(f.KPI_DMO_COMPLIANCE), 2) AS AVG_DMO_COMPLIANCE
FROM RAW.MARKET_PRICES f
JOIN RAW.EXPORT_LEVY e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CPO_PRICE), 2) AS AVG_CPO_PRICE,
  ROUND(AVG(f.KPI_ROTTERDAM_CIF), 2) AS AVG_ROTTERDAM_CIF,
  ROUND(AVG(f.KPI_INDIA_IMPORT_DUTY), 2) AS AVG_INDIA_IMPORT_DUTY,
  ROUND(AVG(f.KPI_DMO_COMPLIANCE), 2) AS AVG_DMO_COMPLIANCE
FROM RAW.MARKET_PRICES f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CPO_PRICE) AS KPI_CPO_PRICE, AVG(KPI_DMO_COMPLIANCE) AS KPI_DMO_COMPLIANCE, AVG(KPI_ROTTERDAM_CIF) AS KPI_ROTTERDAM_CIF, AVG(KPI_INDIA_IMPORT_DUTY) AS KPI_INDIA_IMPORT_DUTY FROM RAW.MARKET_PRICES),
     en AS (SELECT SUM(KPI_EXPORT_VOLUME_MTD) AS KPI_EXPORT_VOLUME_MTD, SUM(KPI_ACTIVE_CONTRACTS) AS KPI_ACTIVE_CONTRACTS, SUM(KPI_B35_MANDATE_IMPACT) AS KPI_B35_MANDATE_IMPACT FROM RAW.EXPORT_LEVY)
  SELECT 1 AS SORT_ORDER, 'CPO Price' AS TITLE, KPI_CPO_PRICE AS VALUE_NUM, 'Rp' || ' ' || LTRIM(TO_VARCHAR(CAST(ROUND((KPI_CPO_PRICE)) AS DECIMAL(38,0)), '999,999,999,999')) || '/kg' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Export Volume (MTD)' AS TITLE, KPI_EXPORT_VOLUME_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_EXPORT_VOLUME_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'MT' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'DMO Compliance' AS TITLE, KPI_DMO_COMPLIANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DMO_COMPLIANCE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Contracts' AS TITLE, KPI_ACTIVE_CONTRACTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_CONTRACTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Rotterdam CIF' AS TITLE, KPI_ROTTERDAM_CIF AS VALUE_NUM, '$' || TO_VARCHAR(CAST(ROUND((KPI_ROTTERDAM_CIF)) AS DECIMAL(38,0))) || '/MT' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'India Import Duty' AS TITLE, KPI_INDIA_IMPORT_DUTY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_INDIA_IMPORT_DUTY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'B35 Mandate Impact' AS TITLE, KPI_B35_MANDATE_IMPACT AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND(((KPI_B35_MANDATE_IMPACT) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'MT' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
