-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT counterparty.ID AS ENTITY_ID, counterparty.NAME AS ENTITY_NAME,
       counterparty.REGION, counterparty.CATEGORY, counterparty.CREDIT_SCORE, counterparty.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.SETTLEMENT_DUE) AS SETTLEMENTS_DUE,
       SUM(observation.SETTLEMENT_LATE) AS SETTLEMENTS_LATE,
       SUM(observation.INVOICE_DUE_USD) AS INVOICE_DUE_USD,
       SUM(observation.INVOICE_SETTLED_USD) AS INVOICE_SETTLED_USD,
       SUM(observation.CREDIT_FOLLOWUP) AS CREDIT_FOLLOWUPS,
       SUM(observation.PAYMENT_COMMITMENT) AS PAYMENT_COMMITMENTS,
       100.0 * (SUM(observation.SETTLEMENT_DUE) - SUM(observation.SETTLEMENT_LATE))
         / NULLIF(SUM(observation.SETTLEMENT_DUE), 0) AS ON_TIME_RATE_PCT,
       MAX_BY(observation.DAYS_OVERDUE, observation.EVENT_DATE) AS LATEST_DAYS_OVERDUE,
       MAX_BY(observation.OPEN_EXPOSURE_USD, observation.EVENT_DATE) AS LATEST_EXPOSURE_USD,
       AVG(observation.LC_HEADROOM_USD) AS AVG_LC_HEADROOM_USD,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.SETTLEMENT_DAILY observation
JOIN RAW.COUNTERPARTIES counterparty ON counterparty.ID = observation.ENTITY_ID
GROUP BY counterparty.ID, counterparty.NAME, counterparty.REGION, counterparty.CATEGORY, counterparty.CREDIT_SCORE, counterparty.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(SETTLEMENT_DUE) AS SETTLEMENTS_DUE, SUM(SETTLEMENT_LATE) AS SETTLEMENTS_LATE,
       SUM(INVOICE_SETTLED_USD) AS INVOICE_SETTLED_USD,
       COUNT_IF(DAYS_OVERDUE > 30) AS COUNTERPARTIES_30D_OVERDUE,
       100.0 * (SUM(SETTLEMENT_DUE) - SUM(SETTLEMENT_LATE)) / NULLIF(SUM(SETTLEMENT_DUE), 0) AS ON_TIME_RATE_PCT
FROM RAW.SETTLEMENT_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.PRODUCT_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH latest AS (
  SELECT ENTITY_ID, DAYS_OVERDUE, OPEN_EXPOSURE_USD FROM RAW.SETTLEMENT_DAILY
  WHERE EVENT_DATE = (SELECT MAX(EVENT_DATE) FROM RAW.SETTLEMENT_DAILY)
)
SELECT counterparty.CATEGORY AS PRODUCT, COUNT(DISTINCT counterparty.ID) AS COUNTERPARTY_COUNT,
       SUM(observation.SETTLEMENT_DUE) AS SETTLEMENTS_DUE,
       SUM(observation.SETTLEMENT_LATE) AS SETTLEMENTS_LATE,
       100.0 * (SUM(observation.SETTLEMENT_DUE) - SUM(observation.SETTLEMENT_LATE))
         / NULLIF(SUM(observation.SETTLEMENT_DUE), 0) AS ON_TIME_RATE_PCT,
       MAX(l.EXPOSURE) AS OPEN_EXPOSURE_USD,
       100.0 * MAX(l.OVERDUE30_EXPOSURE) / NULLIF(MAX(l.EXPOSURE), 0) AS OVERDUE30_PCT
FROM RAW.SETTLEMENT_DAILY observation
JOIN RAW.COUNTERPARTIES counterparty ON counterparty.ID = observation.ENTITY_ID
JOIN (SELECT b.CATEGORY, SUM(latest.OPEN_EXPOSURE_USD) AS EXPOSURE,
             SUM(IFF(latest.DAYS_OVERDUE > 30, latest.OPEN_EXPOSURE_USD, 0)) AS OVERDUE30_EXPOSURE
      FROM latest JOIN RAW.COUNTERPARTIES b ON b.ID = latest.ENTITY_ID GROUP BY b.CATEGORY) l
  ON l.CATEGORY = counterparty.CATEGORY
GROUP BY counterparty.CATEGORY;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(SETTLEMENT_DUE) AS DUE, SUM(SETTLEMENT_LATE) AS LATE,
         SUM(CREDIT_FOLLOWUP) AS FOLLOWUPS, SUM(PAYMENT_COMMITMENT) AS COMMITMENTS,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.SETTLEMENT_DAILY
), latest AS (
  SELECT SUM(OPEN_EXPOSURE_USD) AS EXPOSURE,
         SUM(IFF(DAYS_OVERDUE > 30, OPEN_EXPOSURE_USD, 0)) AS OVERDUE30_EXPOSURE
  FROM RAW.SETTLEMENT_DAILY WHERE EVENT_DATE = (SELECT MAX(EVENT_DATE) FROM RAW.SETTLEMENT_DAILY)
), book AS (SELECT COUNT(*) AS COUNTERPARTY_COUNT FROM RAW.COUNTERPARTIES),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.SHIPPING_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'On-time Settlement Rate' AS TITLE,
         100.0 * (DUE - LATE) / NULLIF(DUE, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Settlements Due', DUE, '' FROM observations
  UNION ALL SELECT 3, 'Late Settlements', LATE, '' FROM observations
  UNION ALL SELECT 4, 'Exposure >30d Overdue', 100.0 * OVERDUE30_EXPOSURE / NULLIF(EXPOSURE, 0), '%' FROM latest
  UNION ALL SELECT 5, 'Open Exposure (USD m)', EXPOSURE / 1e6, '' FROM latest
  UNION ALL SELECT 6, 'Payment Commitment Rate', 100.0 * COMMITMENTS / NULLIF(FOLLOWUPS, 0), '%' FROM observations
  UNION ALL SELECT 7, 'Counterparties', COUNTERPARTY_COUNT, '' FROM book
  UNION ALL SELECT 8, 'Document Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 9, 'Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' AND metrics.SORT_ORDER = 5 THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '999,990.0'))
                WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.PRODUCT_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
