-- Late-settlement risk scoring and credit-desk workload forecast over the synthetic snapshot.
-- Predicts P(counterparty settles an invoice late in the next 14 days) and reports
-- out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.SETTLEMENT_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, b.CATEGORY, b.CREDIT_SCORE, b.MONTHS_TRADING, r.DAYS_OVERDUE,
       AVG(r.LC_HEADROOM_USD) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)
         / NULLIF(AVG(r.LC_HEADROOM_USD) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW), 0)
         AS HEADROOM_7D_VS_30D,
       AVG(r.VESSEL_NOMINATIONS) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS VESSEL_NOMINATIONS_7D,
       SUM(r.SETTLEMENT_LATE) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS LATE_30D,
       IFF(SUM(r.SETTLEMENT_LATE) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 14 FOLLOWING) > 0,
           'LATE', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 14 FOLLOWING) AS FUTURE_DAYS,
       SUM(r.SETTLEMENT_DUE) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 14 FOLLOWING) AS FUTURE_DUE
FROM RAW.SETTLEMENT_DAILY r JOIN RAW.COUNTERPARTIES b ON b.ID = r.ENTITY_ID;

-- Time-based split: hold out the most recent 14 labelled days; train ends 14 days earlier so
-- no training label window overlaps the holdout. Counterparties already more than 30 days overdue are in
-- credit escalation and are excluded from training and evaluation (their next late settlement is trivial).
CREATE VIEW ML.LATE_TRAIN AS
SELECT CATEGORY, CREDIT_SCORE, MONTHS_TRADING, DAYS_OVERDUE, HEADROOM_7D_VS_30D, VESSEL_NOMINATIONS_7D, LATE_30D, LABEL
FROM ML.SETTLEMENT_FEATURES
WHERE FUTURE_DAYS = 14 AND FUTURE_DUE > 0 AND DAYS_OVERDUE <= 30
  AND EVENT_DATE < DATEADD('day', -41, CURRENT_DATE());

CREATE VIEW ML.LATE_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, CREDIT_SCORE, MONTHS_TRADING, DAYS_OVERDUE, HEADROOM_7D_VS_30D,
       VESSEL_NOMINATIONS_7D, LATE_30D, LABEL
FROM ML.SETTLEMENT_FEATURES
WHERE FUTURE_DAYS = 14 AND FUTURE_DUE > 0 AND DAYS_OVERDUE <= 30
  AND EVENT_DATE >= DATEADD('day', -27, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.LATE_RISK_MODEL(
  INPUT_DATA => TABLE(ML.LATE_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.LATE_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.LATE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'CREDIT_SCORE', CREDIT_SCORE, 'MONTHS_TRADING', MONTHS_TRADING,
           'DAYS_OVERDUE', DAYS_OVERDUE, 'HEADROOM_7D_VS_30D', HEADROOM_7D_VS_30D,
           'VESSEL_NOMINATIONS_7D', VESSEL_NOMINATIONS_7D, 'LATE_30D', LATE_30D)):probability:LATE::FLOAT AS P
  FROM ML.LATE_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'LATE', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'LATE', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'LATE', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'LATE', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per counterparty (label unknown, so excluded from features).
CREATE TABLE ML.LATE_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.SETTLEMENT_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.LATE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'CREDIT_SCORE', CREDIT_SCORE, 'MONTHS_TRADING', MONTHS_TRADING,
           'DAYS_OVERDUE', DAYS_OVERDUE, 'HEADROOM_7D_VS_30D', HEADROOM_7D_VS_30D,
           'VESSEL_NOMINATIONS_7D', VESSEL_NOMINATIONS_7D, 'LATE_30D', LATE_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:LATE::FLOAT, 4) AS LATE_PROB_14D,
       CASE WHEN P:probability:LATE::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:LATE::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Portfolio-wide late-settlement forecast (14 days), for credit-desk staffing.
CREATE VIEW ML.DAILY_LATE AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(SETTLEMENT_LATE)::FLOAT AS LATE_COUNT
FROM RAW.SETTLEMENT_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.LATE_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_LATE),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'LATE_COUNT'
);

CREATE TABLE ML.LATE_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS LATE_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.LATE_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
