-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for CPO Trading Analytics
-- ============================================================================
USE DATABASE PALM_OIL_TRADING;
USE SCHEMA ML;

-- ML.FORECAST: CPO_PRICE_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CPO_PRICE_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FORWARD_CURVE'),
  SERIES_COLNAME => 'DELIVERY_MONTH',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.CPO_PRICE_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.CPO_PRICE_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

