-- ============================================================================
-- 99_RESET.SQL — Reset CPO Trading Analytics to clean demo state
-- ============================================================================
USE DATABASE PALM_OIL_TRADING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_PRICES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_POSITIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_PRICES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.POSITION_BOOK REFRESH;
ALTER DYNAMIC TABLE CURATED.FORWARD_CURVE REFRESH;
ALTER DYNAMIC TABLE CURATED.LOGISTICS_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.LEVY_IMPACT REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PALM_OIL_TRADING.RAW.TRADES → 15000
-- SELECT COUNT(*) FROM PALM_OIL_TRADING.RAW.MARKET_PRICES → 200000
-- SELECT COUNT(*) FROM PALM_OIL_TRADING.RAW.LOGISTICS → 10000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_PRICES RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_POSITIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_PRICES RESUME;
